### ISSUE TITLE
我这边在electron-vue中使用这模块会报这个错误

### ISSUE THREAD

**Issue by zss** [code-farmer-i/el-bigdata-table#1]
![image](https://user-images.githubusercontent.com/1480871/58640306-5c7c6780-832b-11e9-8b16-4290f3b3b73e.png)

**Comment by zss** [comment]
不知道有没有好的方法解决

**Comment by code-farmer-i** [comment]
用的是最新的版本吗

**Comment by zss** [comment]
直接使用npm install 模块名 --save 安装的

**Comment by code-farmer-i** [comment]
我这边用electron-vue的脚手架新建了一个项目测了一下，没有问题啊，我这边测试的element-ui的版本是最新版。

**Comment by zss** [comment]
element的版本是2.8.x的版本吗？我的nodejs版本是10.x.x，可以把你的package.json文件发我一下吗？zss_503@163.com

**Comment by code-farmer-i** [comment]
可以的 我测试过2.3.9 - 最新版 加我wx吧 ckang1229

**Comment by zss** [comment]
我是直接用npm install 模块名 --save安装的




| |
zss_503
|
|
邮箱：zss_503@163.com
|

Signature is customized by Netease Mail Master

在2019年05月30日 22:58，code-farmer-i 写道：

用的是最新的版本吗

**Comment by zss** [comment]
目前最新版本是多少




| |
zss_503
|
|
邮箱：zss_503@163.com
|

Signature is customized by Netease Mail Master

在2019年05月30日 22:59，Mark 写道：
我是直接用npm install 模块名 --save安装的




| |
zss_503
|
|
邮箱：zss_503@163.com
|

Signature is customized by Netease Mail Master

在2019年05月30日 22:58，code-farmer-i 写道：

用的是最新的版本吗
