### ISSUE TITLE
列宽小于80px，导致右边有部分列无法正常加载

### ISSUE THREAD

**Issue by xiaowenhai1992** [code-farmer-i/el-bigdata-table#12]
请将table.mixin.js文件第11行修改一下，不然当显示的列有多条小于默认列宽80px时，右边会有部分列无法显示数据。将11行代码修改如下：
      return [position, position += Math.max(realWidth, width?width:minWidth)]
另外，还有一个建议，添加一个类似excess-rows的参数（表格可视区域左方与右方额外渲染的列数）
参数代码：
excessColumns: {
      type: Number,
      default: 10
    },
实现代码：
this.columnStart = start - this.excessColumns > 0 ? start - this.excessColumns:0
      this.columnEnd = end + this.excessColumns < this.columns.length ? end + this.excessColumns : this.columns.length

**Comment by code-farmer-i** [comment]
感觉隐藏列这功能有点鸡肋。。

**Comment by xiaowenhai1992** [comment]
那个最小宽度为80的判断呢，我觉得这个还是有必要修复一下，有时候用的到。比如序号什么的一般都不需要80px
