### ISSUE TITLE
作者你好，如果我的列数多了 也会卡， 你只是隐藏了tr行，td单元格多了 你没隐藏

### ISSUE THREAD

**Issue by livelyPeng** [code-farmer-i/el-bigdata-table#7]
作者你好，如果我的列数多了 也会卡， 你只是隐藏了tr行，td单元格多了 你没隐藏

**Comment by code-farmer-i** [comment]
嗯，几十列应该没问题的吧

**Comment by livelyPeng** [comment]
我能加你QQ吗，我是403802162 QQ  我想进一步寻求帮助，有2个BUG地方

**Comment by TTT822520** [comment]
你好  我这边出现  有500+行 500+列的表格  行当前组件是支持的 但是列一多还是一样卡蹦了 能否同事支持下 列行不卡的情况啊
